version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks: 
      - teste


  servico.atualizar:
    image: maikejordan2010/fiap.atividade03.atualizar:v1
    environment: 
      - ConnectionStrings:${CONNECTION_STRING}
      - RabbitLocal:Endereco=${ENDERECO}
      - RabbitLocal:Porta=${PORTA}
      - RabbitLocal:Usuario=${USUARIO}
      - RabbitLocal:Senha=${SENHA}
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - teste
    depends_on:
      - rabbitmq

  servico.excluir:
    image: maikejordan2010/fiap.atividade03.excluir:v1
    environment: 
      - ConnectionStrings:${CONNECTION_STRING}
      - RabbitLocal:Endereco=${ENDERECO}
      - RabbitLocal:Porta=${PORTA}
      - RabbitLocal:Usuario=${USUARIO}
      - RabbitLocal:Senha=${SENHA}
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - teste
    depends_on:
      - rabbitmq

  servico.cadastrar:
    image: maikejordan2010/fiap.atividade03.cadastrar:v1
    environment: 
      - ConnectionStrings:${CONNECTION_STRING}
      - RabbitLocal:Endereco=${ENDERECO}
      - RabbitLocal:Porta=${PORTA}
      - RabbitLocal:Usuario=${USUARIO}
      - RabbitLocal:Senha=${SENHA}
    build: 
      context: .
      dockerfile: Dockerfile
    networks: 
      - teste
    depends_on:
      - rabbitmq


  atividade03.api:
    image: atividade03.api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=${CONNECTION_STRING}
      - Cors:Urls=${URLS_LIBERADAS}
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    expose:
      - 8080
    networks: 
      - teste
    depends_on:
      - rabbitmq
      - servico.atualizar
      - servico.cadastrar
      - servico.excluir

networks:
  teste:
    driver: bridge
    
