version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    networks: 
      - teste

  atividade03.api:
    image: atividade03.api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment: 
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings:DefaultConnection=${CONNECTION_STRING}
      - Cors:Urls=${URLS_LIBERADAS}
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8080:8080
    expose:
      - 8080
    networks: 
      - teste
    depends_on:
      - rabbitmq

networks:
  teste:
    driver: bridge
    
